service: hello-world-tutorial

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

functions:
  main:
    handler: hello.handler
    events:
      - http:
          method: GET
          path: /hello